matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: generic
    - os: osx
      osx_image: xcode7.3
      language: generic
install:
  - source ./.travis-install-swift.sh
cache:
  directories:
    - $HOME/.swift
script:
  - cd ./source-layout-sample && swift build && swift test
